- name: Ensure that docker is well installed
  hosts: wrk
  become: yes
  vars:
    sudoers:
      - thomas
  tasks:
    - name: Make sure we have a 'wheel' group
      group:
        name: wheel
        state: present

    - name: Allow 'wheel' group to have passwordless sudo
      lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: '^%wheel'
        line: '%wheel ALL=(ALL) NOPASSWD: ALL'
        validate: visudo -cf %s

    - name: Add sudoers users to wheel group
      user:
        name: "{{ item }}"
        groups: wheel
        append: yes
      with_items: "{{ sudoers }}"

    - name: Ensure that docker are well isntalled
      yum:
        name: docker-ce
        enablerepo: docker-ce-stable
        state: present

    - name: Ensure that docker are well started
      service:
        name: docker
        state: started
